export const OPERATIONS: string[] = [
  'Eternity Vault',
  "Karagga's Palace",
  'Explosive Conflict',
  'Terror From Beyond',
  'Scum and Villainy',
  'Dread Fortress',
  'Dread Palace',
  'Ravagers',
  'Temple of Sacrifice',
  'Gods from the Machine',
  'Nature of Progress (Dxun)',
  'The R-4 Anomaly',
  'Worldbreaker Monolith',
  'Hive of the Mountain Queen',
  'Golden Fury',
  'Eyeless',
  'Propagator Core XR-53',
  'Xenoanalyst II',
  'Hateful Entity',
  'Dreadful Entity',
  'Random',
  'Poll',
];
